version: "3.7"
services:
  db:
    image: postgres:15
    container_name: hotello_db
    env_file:
      - .env-prod
    ports:
      - "6432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: hotello_redis

  hotello:
    build:
      context: .
    container_name: hotello_app
    env_file:
      - .env-prod
    command:
      - "/hotello/docker/app.sh"
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - "9000:8000"

  celery:
    build:
      context: .
    container_name: hotello_celery
    command: ["/hotello/docker/celery.sh", "celery"]
    env_file:
      - .env-prod
    depends_on:
      - redis

  celery_flower:
    build:
      context: .
    container_name: hotello_celery_flower
    command: ["/hotello/docker/celery.sh", "flower"]
    env_file:
      - .env-prod
    depends_on:
      - redis
      - celery


